#!/usr/bin/env bash


if [ -d ./.git ]; then
    URL=$(git remote -v | grep fetch | sed 's/origin//' | sed 's/(fetch)//')
    echo "Opening url "$URL
    open $URL
else
  echo "There is no .git repo here"
fi
