#!/usr/bin/env bash

RED=`tput setaf 1`
GREEN=`tput setaf 2`
NOCOLOR=`tput sgr0`


FILE_PATH=$PWD

# echo ${PWD/#$HOME/'~'}

echo -e "Adding  ${RED}"$1"${NOCOLOR} located in  ${RED}"$FILE_PATH"${NOCOLOR} to the local bin folder" 
echo $1 >> $HOME/.my_bash_scripts/installed_scripts
chmod a+x $1
cd /usr/local/bin/


ln -s $FILE_PATH/$1 $1

chmod +x $1

